export const BOARD_GET_SUCCESSFULL = "BOARD_GET_SUCCESSFULL";
export const SET_BOARD_ACTIVE = "SET_BOARD_ACTIVE";
export const STOP_LOGIN_PROCESSING = "STOP_LOGIN_PROCESSING";
export const LOGIN_PROCESSING = "LOGIN_PROCESSING";
export const STOP_BOARD_PROCESSING = "STOP_BOARD_PROCESSING";
export const BOARD_PROCESSING = "BOARD_PROCESSING";
