export const LOGIN_SUCCESSFULL = "LOGIN_SUCCESSFULL";
export const STOP_LOGIN_PROCESSING = "STOP_LOGIN_PROCESSING";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";
export const LOGIN_PROCESSING = "LOGIN_PROCESSING";